<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartTrinity.App.FuelStation\SmartTrinity.App.FuelStation.csproj" />
    <ProjectReference Include="..\SmartTrinity.Sales\SmartTrinity.App.Sales.csproj" />
  </ItemGroup>

</Project>
