<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Communication\CommunicationManager\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartTrinityConsole.Core\SmartTrinityApi.Core.csproj" />
  </ItemGroup>

</Project>
